In [2]:
!python make_map.py --weights_path checkpoints480/yolov3_ckpt_999.pth --model_def config/yolov3-custom480.cfg \
--data_config config/custom480_rl.data \
--img_size=480 --batch_size 1 --class_path data/custom480/classes.names \
--save_dir /home/cutz/SAR_OD/EfficientObjectDetection/data/800/base_dir_metric_fd

Namespace(batch_size=1, class_path='data/custom480/classes.names', conf_thres=0.001, data_config='config/custom480_rl.data', img_size=480, iou_thres=0.5, model_def='config/yolov3-custom480.cfg', n_cpu=8, nms_thres=0.5, save_dir='/home/cutz/SAR_OD/EfficientObjectDetection/data/800/base_dir_metric_fd', weights_path='checkpoints480/yolov3_ckpt_999.pth')
Compute mAP...
Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 1196.66it/s]
[[1. 0.]
 [0. 0.]]
P0036_4800_5600_6600_7400 saved
Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5229.81it/s]
[[0. 1.]
 [0. 0.]]
P0055_1200_2000_3600_4400 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4337.44it/s]
[[1. 0.]
 [0. 0.]]
P0044_2400_3200_3000_3800 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4766.25it/s]
[[0. 1.]
 [0. 0.]]
P0078_2400_3200_4800_5600 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4006.02it/s]
[[0. 1.]
 [0. 0.]]
P

[[0. 0.]
 [0. 0.]]
P0019_5660_6460_5400_6200 saved
[[0. 0.]
 [0. 0.]]
P0080_2400_3200_4200_5000 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0072_600_1400_3000_3800_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0071_600_1400_600_1400 saved
Detecting objects:   3%|▌                     | 35/1308 [00:02<01:19, 16.11it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0038_2400_3200_2400_3200_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5242.88it/s]
[[0. 0.]
 [0. 1.]]
P0004_3000_3800_0_800 saved
[[0. 0.]
 [0. 0.]]
P0072_600_1400_3000_3800 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: 


Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5184.55it/s]
[[0. 0.]
 [1. 0.]]
P0105_1800_2600_19200_20000 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0040_4800_5600_6000_6800_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0025_2400_3200_2400_3200 saved
Detecting objects:   5%|█▏                    | 68/1308 [00:03<00:48, 25.38it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0071_3000_3800_4200_5000_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5229.81it/s]
[[0. 1.]
 [0. 0.]]
P0016_3600_4400_0_800 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input fi

Detecting objects:   8%|█▌                   | 101/1308 [00:04<00:45, 26.32it/s][[0. 0.]
 [0. 0.]]
P0062_1200_2000_2400_3200 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4993.22it/s]
[[0. 0.]
 [1. 0.]]
P0063_600_1400_6000_6800 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5714.31it/s]
[[0. 0.]
 [0. 1.]]
P0040_4800_5600_2400_3200 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0033_1800_2600_3600_4400_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0135_3000_3800_5400_6200_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4860.14it/s]
[[1. 1.]
 [0. 0.


Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5599.87it/s]
[[1. 0.]
 [0. 0.]]
P0015_1800_2600_3600_4400 saved
[[0. 0.]
 [0. 0.]]
P0047_3600_4400_0_800 saved
Detecting objects:  11%|██▏                  | 139/1308 [00:05<00:46, 25.07it/s][[0. 0.]
 [0. 0.]]
P0015_5400_6200_1800_2600 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5660.33it/s]
[[0. 1.]
 [0. 0.]]
P0096_3200_4000_1200_2000 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0010_4200_5000_1200_2000_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5349.88it/s]
[[0.         0.        ]
 [0.66666667 0.        ]]
P0126_4800_5600_6600_7400 saved
Detecting objects:  11%|██▎                  | 142/1308 [00:06<00:46, 24.84it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:


Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5899.16it/s]
[[0. 0.]
 [0. 1.]]
P0042_3000_3800_4800_5600 saved
Detecting objects:  14%|██▊                  | 177/1308 [00:07<00:43, 26.09it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0027_5400_6200_6600_7400_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0004_4262_5062_2400_3200 saved
[[0. 0.]
 [0. 0.]]
P0049_600_1400_7000_7800 saved
[[0. 0.]
 [0. 0.]]
P0027_5400_6200_6600_7400 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 3426.72it/s]
[[0.         0.        ]
 [1.         0.66666667]]
P0093_0_800_1200_2000 saved
Detecting objects:  14%|██▉                  | 181/1308 [00:07<00:40, 27.66it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_r

[[0. 0.]
 [0. 0.]]
P0063_3600_4400_1200_2000 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0063_3600_4400_1200_2000_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4447.83it/s]
[[0. 0.]
 [0. 1.]]
P0006_1800_2600_1800_2600 saved
Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5005.14it/s]
[[1. 0.]
 [0. 0.]]
P0105_3000_3800_18600_19400 saved
[[0. 0.]
 [0. 0.]]
P0063_3600_4400_1200_2000 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4443.12it/s]
[[0. 0.]
 [0. 1.]]
P0027_2400_3200_3600_4400 saved
Detecting objects:  17%|███▍                 | 217/1308 [00:08<00:44, 24.25it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0029_5400_

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5178.15it/s]
[[0. 0.]
 [0. 1.]]
P0098_1200_2000_4800_5600 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0066_3600_4400_600_1400_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0057_1800_2600_0_800 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0113_4200_5000_3600_4400_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 3994.58it/s]
[[0. 1.]
 [0. 0.]]
P0069_600_1400_5900_6700 saved
Detecting objects:  19%|████                 | 252/1308 [00:10<00:38, 27.48it/s][[0. 0.]
 [0. 0.]]
P0066_3600_4400_600_1400 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets

[[1. 1.]
 [0. 0.]]
P0067_1800_2600_3600_4400 saved
Detecting objects:  21%|████▌                | 281/1308 [00:11<00:34, 29.45it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0033_3600_4400_2400_3200_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0002_600_1400_8689_9489 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0098_0_800_2400_3200_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0063_3600_4400_1200_2000 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0020_3000_3800_3000_3800_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0.


Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 7061.12it/s]
[[0. 1.]
 [0. 0.]]
P0105_1800_2600_15600_16400 saved
Detecting objects:  24%|█████                | 315/1308 [00:12<00:39, 25.40it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0012_5400_6200_4800_5600_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0032_4200_5000_2400_3200 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0005_4200_5000_3600_4400_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0033_1800_2600_7800_8600 saved
[[0. 0.]
 [0. 0.]]
P0012_5400_6200_4800_5600 saved
Detecting objects:  24%|█████                | 318/1308 [00:12<00:38, 25.72it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/

[[0. 0.]
 [0. 0.]]
P0063_600_1400_4200_5000 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5622.39it/s]
[[0. 0.]
 [1. 0.]]
P0077_1800_2600_4200_5000 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0137_51_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 1.]
 [0. 0.]]
P0105_1800_2600_15600_16400 saved
Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5159.05it/s]
[[0. 1.]
 [0. 0.]]
P0026_3600_4400_3000_3800 saved
[[0. 0.]
 [0. 0.]]
P0137_51 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 3799.19it/s]
[[0. 1.]
 [0. 1.]]
P0102_1800_2600_3000_3800 saved
Detecting objects:  27%|█████▋               | 353/1308 [00:13<00:36, 26.51it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/la

[[0. 0.]
 [1. 0.]]
P0038_2400_3200_2400_3200 saved
Detecting objects:  29%|██████               | 379/1308 [00:14<00:35, 25.90it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0137_81_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 1.]]
P0033_3600_4400_2400_3200 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0071_3000_3800_4200_5000_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0005_4200_5000_3600_4400 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0109_3600_4400_7200_8000_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[1. 0.]
 [0. 0.]]
P0137_

Detecting objects:  31%|██████▌              | 412/1308 [00:15<00:36, 24.72it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0023_0_800_0_800_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0060_1200_2000_3000_3800 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0064_2400_3200_600_1400_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0020_3000_3800_3000_3800 saved
[[0. 0.]
 [0. 0.]]
P0023_0_800_0_800 saved
Detecting objects:  32%|██████▋              | 415/1308 [00:16<00:35, 25.02it/s][[0. 0.]
 [0. 0.]]
P0064_2400_3200_600_1400 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 3148.88it/s]
[[0.         0.57142857]
 [0.         0.        ]]
P0111_5400_6200

[[0. 0.]
 [0. 1.]]
P0024_5400_6200_1200_2000 saved
Detecting objects:  34%|███████▏             | 449/1308 [00:17<00:35, 24.43it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0133_3600_4400_600_1400_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 3452.10it/s]
[[0.  0. ]
 [0.8 1. ]]
P0091_1200_2000_3000_3800 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0113_4200_5000_3600_4400_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0017_4200_5000_4200_5000 saved
[[0. 1.]
 [0. 1.]]
P0133_3600_4400_600_1400 saved
Detecting objects:  35%|███████▎             | 452/1308 [00:17<00:33, 25.74it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/

[[0. 0.]
 [0. 0.]]
P0033_1800_2600_7800_8600 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0046_2400_3200_600_1400_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0049_600_1400_7000_7800 saved
Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4655.17it/s]
[[0. 0.]
 [1. 1.]]
P0114_1800_2600_9000_9800 saved
[[0. 0.]
 [0. 0.]]
P0046_2400_3200_600_1400 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0069_600_1400_5900_6700_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 6213.78it/s]
[[0. 1.]
 [0. 0.]]
P0051_2400_3200_3600_4400 saved
Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5599.87it/s]

Detecting objects:  39%|████████▎            | 515/1308 [00:19<00:24, 31.87it/s][[0. 0.]
 [0. 0.]]
P0049_1800_2600_4200_5000 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0039_4800_5600_1200_2000_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[1. 0.]
 [0. 0.]]
P0098_600_1400_4200_5000 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0096_3200_4000_1200_2000_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5029.14it/s]
[[0. 0.]
 [0. 1.]]
P0064_2400_3200_2400_3200 saved
[[0. 0.]
 [0. 1.]]
P0039_4800_5600_1200_2000 saved
Detecting objects:  40%|████████▎            | 519/1308 [00:19<00:27, 29.16it/s][[0. 1.]
 [0. 0.]]
P0096_3200_4000_1200_2000 save


Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 7108.99it/s]
[[1. 0.]
 [0. 0.]]
P0058_1800_2600_0_800 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0055_3900_4700_3000_3800_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5809.29it/s]
[[1. 0.]
 [1. 0.]]
P0063_600_1400_6000_6800 saved
Detecting objects:  42%|████████▉            | 555/1308 [00:21<00:25, 29.38it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0026_1200_2000_1800_2600_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5809.29it/s]
[[1. 0.]
 [1. 0.]]
P0092_600_1400_1200_2000 saved
[[0. 0.]
 [0. 0.]]
P0


Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5065.58it/s]
[[0. 0.]
 [1. 0.]]
P0112_3000_3800_600_1400 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0006_4200_5000_7200_8000_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[1. 0.]
 [0. 0.]]
P0126_5400_6200_11400_12200 saved
Detecting objects:  45%|█████████▍           | 588/1308 [00:22<00:28, 25.23it/s][[0. 0.]
 [0. 0.]]
P0044_1200_2000_3000_3800 saved
[[0. 0.]
 [1. 0.]]
P0006_4200_5000_7200_8000 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0081_600_1400_3000_3800_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5461.33it/s]
[[0. 1.]
 [0. 0.]]
P0036_2400_3200_4800_5600 s


Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5785.25it/s]
[[1. 0.]
 [0. 0.]]
P0133_3600_4400_1200_2000 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0007_1200_2000_4200_5000_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 0.]]
P0134_6600_7400_2400_3200 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 6232.25it/s]
[[0. 0.]
 [0. 1.]]
P0043_6700_7500_6000_6800 saved
Detecting objects:  48%|██████████           | 625/1308 [00:23<00:23, 29.12it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0026_1200_2000_3600_4400_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 1.]]
P0007_1200_2000_4200_5000 saved

Computing AP: 100%|██████████████████████████

Detecting objects:  50%|██████████▍          | 653/1308 [00:24<00:23, 27.95it/s][[0. 1.]
 [1. 0.]]
P0079_3600_4400_2400_3200 saved
[[0. 0.]
 [0. 1.]]
P0007_1200_2000_4200_5000 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4987.28it/s]
[[1. 0.]
 [1. 1.]]
P0036_4800_5600_6600_7400 saved
Detecting objects:  50%|██████████▌          | 656/1308 [00:24<00:24, 26.62it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0001_0_800_9000_9800_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4782.56it/s]
[[0.   0.25]
 [0.   0.  ]]
P0113_4200_5000_3600_4400 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5691.05it/s]
[[0. 0.]
 [1. 0.]]
P0020_3600_4400_0_800 saved
[[0. 0.]
 [1. 1.]]
P0001_0_800_9000_9800 saved
Detecting objects:  50%|██████████▌    

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 3594.09it/s]
[[1. 0.]
 [0. 0.]]
P0077_1200_2000_4800_5600 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0092_1800_2600_4200_5000_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 1.]
 [0. 0.]]
P0126_2400_3200_5400_6200 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4614.20it/s]
[[0.  0. ]
 [0.7 1. ]]
P0109_3600_4400_7800_8600 saved
Detecting objects:  53%|███████████          | 692/1308 [00:26<00:24, 24.85it/s][[0.5 0. ]
 [0.  0. ]]
P0092_1800_2600_4200_5000 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0026_3600_4400_3000_3800_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|███████████████████


Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5329.48it/s]
[[1. 1.]
 [0. 1.]]
P0008_1800_2600_4800_5600 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5249.44it/s]
[[1. 0.]
 [1. 0.]]
P0112_3000_3800_600_1400 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0093_1800_2600_1800_2600_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5949.37it/s]
[[1. 0.]
 [1. 0.]]
P0057_600_1400_600_1400 saved
Detecting objects:  56%|███████████▋         | 730/1308 [00:27<00:14, 38.73it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0071_600_1400_600_1400_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|


Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4809.98it/s]
[[1. 1.]
 [0. 1.]]
P0039_3600_4400_4800_5600 saved
[[0.68181818 0.        ]
 [0.24193548 0.        ]]
P0120_3000_3800_9000_9800 saved
Detecting objects:  58%|████████████▎        | 765/1308 [00:28<00:13, 39.16it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0007_3600_4400_1800_2600_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[1. 1.]
 [1. 0.]]
P0044_2400_3200_3000_3800 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0005_4200_5000_3600_4400_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5322.72it/s]
[[0. 1.]
 [0. 0.]]
P0035_5400_6200_1800_2600 saved
/home/cutz/SAR

[[0. 0.]
 [0. 0.]]
P0073_600_1400_3600_4400 saved
Detecting objects:  61%|████████████▊        | 800/1308 [00:29<00:17, 29.17it/s][[0. 0.]
 [0. 0.]]
P0137_20 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5059.47it/s]
[[1. 1.]
 [0. 0.]]
P0124_4800_5600_4800_5600 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0072_2400_3200_4800_5600_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4378.19it/s]
[[1. 0.]
 [0. 0.]]
P0137_69 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0008_600_1400_9000_9800_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5223.29it/s]


[[1. 1.]
 [0. 0.]]
P0032_4200_5000_6600_7400 saved
Detecting objects:  64%|█████████████▍       | 837/1308 [00:30<00:16, 28.38it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0077_1800_2600_4200_5000_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[1. 0.]
 [0. 0.]]
P0098_600_1400_4200_5000 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5468.45it/s]
[[0. 1.]
 [1. 1.]]
P0067_1200_2000_3600_4400 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0087_1800_2600_2400_3200_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [1. 0.]]
P0077_1800_2600_4200_5000 saved
Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4481.09it/s]
[[0. 1.]
 [0. 1.]]
P0004_1200_2000_3000_3800 sav

[[0. 1.]
 [0. 0.]]
P0098_0_800_2400_3200 saved
[[1. 0.]
 [0. 0.]]
P0006_2400_3200_4800_5600 saved
Detecting objects:  67%|█████████████▉       | 871/1308 [00:32<00:17, 24.93it/s][[0. 0.]
 [0. 0.]]
P0137_20 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0051_2400_3200_3600_4400_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 3802.63it/s]
[[0.         0.90909091]
 [0.         0.8       ]]
P0088_0_800_1800_2600 saved
[[0. 0.]
 [0. 0.]]
P0082_0_800_0_800 saved
[[0. 1.]
 [0. 0.]]
P0051_2400_3200_3600_4400 saved
Detecting objects:  67%|██████████████       | 875/1308 [00:32<00:15, 27.53it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0044_1200_2000_3000_3800_1.txt"
  boxes = tor

Detecting objects:  69%|██████████████▌      | 905/1308 [00:33<00:16, 25.15it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0012_0_800_7800_8600_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4922.89it/s]
[[0. 0.]
 [1. 1.]]
P0042_3600_4400_6000_6800 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0091_1200_2000_3000_3800_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 1.]
 [0. 0.]]
P0033_3600_4400_1200_2000 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0004_3600_4400_7200_8000_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_pat

[[0. 1.]
 [0. 0.]]
P0126_2400_3200_5400_6200 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5384.22it/s]
[[0. 1.]
 [1. 0.]]
P0060_1800_2600_6000_6800 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4733.98it/s]
[[0. 0.]
 [0. 0.]]
P0137_20 saved
Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5262.61it/s]
[[0. 0.]
 [1. 1.]]
P0031_5160_5960_5400_6200 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0004_3600_4400_7200_8000_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5295.84it/s]
[[1. 0.]
 [1. 1.]]
P0060_3000_3800_3600_4400 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 6017.65it/s]
[[1. 0.]
 [0. 0.]]
P0014_2400_3200_2400_3200 saved
Detecting objects:  72%|███████████████▏     | 94

[[1. 0.]
 [1. 0.]]
P0092_600_1400_1200_2000 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0105_2400_3200_13200_14000_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4843.31it/s]
[[1. 0.]
 [0. 0.]]
P0004_4262_5062_2400_3200 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0135_1200_2000_7800_8600_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [1. 0.]]
P0013_3000_3800_3600_4400 saved
[[0. 0.]
 [0. 1.]]
P0105_2400_3200_13200_14000 saved
Detecting objects:  75%|███████████████▋     | 980/1308 [00:36<00:12, 27.00it/s][[1. 1.]
 [0. 0.]]
P0135_1200_2000_7800_8600 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5548.02it/s]
[[1. 1.]
 [1. 1.]]
P0036_4800_5600_6600_7400 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0009_1200_2000_4800_5600_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5489.93it/s]
[[1. 1.]
 [0. 0.]]
P0039_4800_5600_0_800 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4865.78it/s]
[[0. 0.]
 [1. 1.]]
P0052_600_1400_6600_7400 saved
Detecting objects:  78%|███████████████▌    | 1016/1308 [00:37<00:11, 26.52it/s][[1. 1.]
 [0. 0.]]
P0009_1200_2000_4800_5600 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0013_4560_5360_1200_2000_0.txt"
  boxes = torch.from_numpy(np.loadtx

Detecting objects:  81%|████████████████    | 1053/1308 [00:38<00:09, 28.15it/s][[1. 1.]
 [0. 0.]]
P0009_4200_5000_6600_7400 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4766.25it/s]
[[0.16666667 0.66666667]
 [0.         0.        ]]
P0006_0_800_7800_8600 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0088_0_800_1800_2600_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4346.43it/s]
[[0.  0. ]
 [0.  0.5]]
P0034_600_1400_9289_10089 saved
Detecting objects:  81%|████████████████▏   | 1056/1308 [00:38<00:09, 25.74it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0105_2400_3200_13200_14000_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).res


Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4271.19it/s]
[[0.         0.        ]
 [0.57142857 0.5       ]]
P0085_1800_2600_3000_3800 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0109_3600_4400_7800_8600_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[1. 0.]
 [0. 0.]]
P0105_3000_3800_18600_19400 saved
Detecting objects:  83%|████████████████▋   | 1089/1308 [00:40<00:08, 26.45it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0027_4800_5600_2400_3200_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5419.00it/s]
[[0. 1.]
 [0. 0.]]
P0059_1800_2600_8000_8800 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: 


Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5584.96it/s]
[[0. 0.]
 [0. 1.]]
P0073_600_1400_3600_4400 saved
Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5356.71it/s]
[[1. 1.]
 [0. 0.]]
P0048_1200_2000_7300_8100 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5433.04it/s]
[[1. 1.]
 [1. 1.]]
P0067_1800_2600_3600_4400 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5023.12it/s]
[[0. 0.]
 [1. 0.]]
P0010_5156_5956_3600_4400 saved
Detecting objects:  86%|█████████████████▏  | 1124/1308 [00:41<00:07, 25.96it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0058_1800_2600_0_800_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4707.41it/s]
[[0. 0.]
 [0. 1.]]
P0127_3600_4400_4800_5600 saved

Computi

[[0. 0.]
 [1. 1.]]
P0105_1200_2000_19200_20000 saved
Detecting objects:  88%|█████████████████▋  | 1154/1308 [00:42<00:06, 24.88it/s][[0. 0.]
 [0. 0.]]
P0007_2400_3200_2400_3200 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0019_5400_6200_5400_6200_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 0.]
 [0. 1.]]
P0060_1200_2000_3000_3800 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5405.03it/s]
[[1. 1.]
 [1. 0.]]
P0009_4200_5000_6600_7400 saved
[[0. 1.]
 [0. 1.]]
P0019_5400_6200_5400_6200 saved
Detecting objects:  89%|█████████████████▋  | 1158/1308 [00:42<00:05, 27.68it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0015_5400_6200_1800_2600_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1,


Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5801.25it/s]
[[1. 0.]
 [0. 1.]]
P0076_0_800_3600_4400 saved
Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5262.61it/s]
[[1. 1.]
 [1. 1.]]
P0010_0_800_8400_9200 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0028_4200_5000_3000_3800_1.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))
[[0. 1.]
 [0. 1.]]
P0046_1200_2000_3000_3800 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 6026.30it/s]
[[1. 1.]
 [1. 1.]]
P0040_4800_5600_2400_3200 saved
[[1. 0.]
 [0. 1.]]
P0028_4200_5000_3000_3800 saved
Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5974.79it/s]
[[1. 1.]
 [1. 0.]]
P0032_4200_5000_6600_7400 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/datase

[[1. 0.]
 [0. 0.]]
P0126_5400_6200_11400_12200 saved
[[1. 0.]
 [0. 0.]]
P0043_1200_2000_6600_7400 saved
[[1. 0.]
 [0. 0.]]
P0117_1200_2000_3600_4400 saved
Detecting objects:  94%|██████████████████▊ | 1228/1308 [00:45<00:02, 27.63it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0039_4800_5600_0_800_2.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4681.14it/s]
[[1.  0.5]
 [1.  0.6]]
P0085_1800_2600_2400_3200 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0065_2400_3200_3000_3800_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 5256.02it/s]
[[0. 0.]
 [1. 0.]]
P0063_600_1400_4200_5000 

Detecting objects:  96%|███████████████████▎| 1261/1308 [00:46<00:01, 26.25it/s][[0. 1.]
 [0. 0.]]
P0064_1800_2600_1800_2600 saved
[[1. 1.]
 [0. 0.]]
P0048_1200_2000_7300_8100 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4837.72it/s]
[[0.  0.5]
 [0.  0. ]]
P0126_600_1400_3600_4400 saved
Detecting objects:  97%|███████████████████▎| 1264/1308 [00:46<00:01, 25.88it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0107_0_800_2400_3200_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4882.78it/s]
[[0.66666667 0.5       ]
 [0.         1.        ]]
P0132_3000_3800_9926_10726 saved

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4215.38it/s]
[[0.         0.41935484]
 [0.         0.125     ]]
P0109_3600_4400_7200_8000 saved
[[1. 0.]
 [0. 0.]]
P01

[[1. 1.]
 [0. 0.]]
P0062_1200_2000_2400_3200 saved
Detecting objects:  99%|███████████████████▊| 1299/1308 [00:47<00:00, 25.64it/s]/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0010_4200_5000_1200_2000_3.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 3675.99it/s]
[[0.66666667 0.        ]
 [0.375      1.        ]]
P0089_1200_2000_3600_4400 saved
/home/cutz/SAR_OD/PyTorch-YOLOv3-master/utils/datasets.py:107: UserWarning: loadtxt: Empty input file: "/media/data2/dataset/SSDD/800/train_rl/480/labels/P0027_2400_3200_3600_4400_0.txt"
  boxes = torch.from_numpy(np.loadtxt(label_path).reshape(-1, 5))

Computing AP: 100%|█████████████████████████████| 1/1 [00:00<00:00, 4341.93it/s]
[[0.1 0. ]
 [0.  0. ]]
P0125_2400_3200_9600_10400 saved
[[1. 0.]
 [0. 0.]]
P0010_4200_5000_1200_2000 saved
Detecting